using System.Threading.Tasks;
using Xunit;
using Xunit.Abstractions;
using AccessibleTaskManager.Services;

namespace AccessibleTaskManager.Tests
{
    public class HardwareDetailServiceTests
    {
        private readonly ITestOutputHelper _output;

        public HardwareDetailServiceTests(ITestOutputHelper output)
        {
            _output = output;
        }

        [Theory]
        [InlineData("cpu")]
        [InlineData("ram")]
        [InlineData("disk")]
        [InlineData("network")]
        [InlineData("gpu")]
        [InlineData("battery")]
        public async Task GetHardwareDetailsAsync_ReturnsDetailedSpecs(string id)
        {
            var service = new HardwareDetailService();
            string details = await service.GetHardwareDetailsAsync(id);
            _output.WriteLine($"=== {id.ToUpper()} DETAILS ===\n{details}\n");
            Assert.False(string.IsNullOrWhiteSpace(details));
            Assert.Contains("\n", details); // Multiple lines of specs
        }

        [Theory]
        [InlineData(34, 0, "DDR5")]
        [InlineData(26, 0, "DDR4")]
        [InlineData(24, 0, "DDR3")]
        [InlineData(20, 0, "DDR2")]
        [InlineData(19, 0, "DDR")]
        [InlineData(30, 0, "LPDDR4")]
        [InlineData(35, 0, "LPDDR5")]
        [InlineData(27, 0, "LPDDR")]
        [InlineData(32, 0, "HBM")]
        [InlineData(33, 0, "HBM2")]
        [InlineData(36, 0, "HBM3")]
        [InlineData(0, 26, "DDR4")]
        [InlineData(0, 24, "DDR3")]
        [InlineData(0, 0, "DDR / SDRAM")]
        public void DecodeSmbiosMemoryType_IdentifiesGenerationsCorrectly(uint smbiosType, uint legacyType, string expected)
        {
            string result = HardwareDetailService.DecodeSmbiosMemoryType(smbiosType, legacyType);
            Assert.Equal(expected, result);
        }

        [Fact]
        public void ParseBatteryHealthXml_ValidXml_ReturnsCapacityAndCycles()
        {
            string mockXml = @"<?xml version=""1.0"" encoding=""utf-8""?>
<BatteryReport xmlns=""http://schemas.microsoft.com/battery/2012"">
  <Batteries>
    <Battery>
      <DesignCapacity>52000</DesignCapacity>
      <FullChargeCapacity>46800</FullChargeCapacity>
      <CycleCount>142</CycleCount>
      <Manufacturer>SMP</Manufacturer>
      <SerialNumber>987654321</SerialNumber>
    </Battery>
  </Batteries>
</BatteryReport>";

            var (design, full, cycles, mfg, serial) = HardwareDetailService.ParseBatteryHealthXml(mockXml);

            Assert.Equal(52000, design);
            Assert.Equal(46800, full);
            Assert.Equal(142, cycles);
            Assert.Equal("SMP", mfg);
            Assert.Equal("987654321", serial);
        }

        [Fact]
        public void ParseBatteryHealthXml_CorruptOrEmptyXml_ReturnsZerosSafely()
        {
            var (design1, full1, cycles1, mfg1, serial1) = HardwareDetailService.ParseBatteryHealthXml(string.Empty);
            Assert.Equal(0, design1);
            Assert.Equal(0, full1);
            Assert.Equal(0, cycles1);
            Assert.Empty(mfg1);
            Assert.Empty(serial1);

            var (design2, full2, cycles2, mfg2, serial2) = HardwareDetailService.ParseBatteryHealthXml("<invalid>xml");
            Assert.Equal(0, design2);
            Assert.Equal(0, full2);
            Assert.Equal(0, cycles2);
            Assert.Empty(mfg2);
            Assert.Empty(serial2);
        }

        [Fact]
        public async Task GenerateSystemSnapshotAsync_ReturnsCleanSimpleTextReport()
        {
            var service = new HardwareDetailService();
            string snapshot = await service.GenerateSystemSnapshotAsync();

            _output.WriteLine($"=== SYSTEM SNAPSHOT ===\n{snapshot}\n");

            Assert.False(string.IsNullOrWhiteSpace(snapshot));
            Assert.Contains("System Diagnostic Snapshot", snapshot);
            Assert.Contains("[Operating System & Device]", snapshot);
            Assert.Contains("OS:", snapshot);
            Assert.Contains("[Processor (CPU)]", snapshot);
            Assert.Contains("[Memory (RAM)]", snapshot);
            Assert.Contains("[Storage (Disk)]", snapshot);
            Assert.Contains("[Network & Connectivity]", snapshot);

            // Verify no markdown syntax or trailing footer
            Assert.DoesNotContain("# System Diagnostic Snapshot", snapshot);
            Assert.DoesNotContain("## Operating System", snapshot);
            Assert.DoesNotContain("*Generated by", snapshot);
            Assert.DoesNotContain("---", snapshot);
        }

        [Fact]
        public async Task GetHardwareDetailsAsync_RamDetails_IncludesCachedStandbyAndFree()
        {
            var service = new HardwareDetailService();
            string ramDetails = await service.GetHardwareDetailsAsync("ram");

            _output.WriteLine($"=== RAM DETAILS ===\n{ramDetails}\n");

            Assert.Contains("Total Physical Memory:", ramDetails);
            Assert.Contains("In Use:", ramDetails);
            Assert.Contains("Cached (Standby):", ramDetails);
            Assert.Contains("Free Memory:", ramDetails);
            Assert.Contains("Available:", ramDetails);
            Assert.Contains("Committed:", ramDetails);
        }

        [Fact]
        public async Task FlushMemoryCacheAsync_FlushesAndReturnsValidMetrics()
        {
            var service = new HardwareDetailService();
            var (trimmedProcesses, freedBytes, updatedDetails) = await service.FlushMemoryCacheAsync();

            _output.WriteLine($"Flushed {trimmedProcesses} processes, freed {freedBytes} bytes.\n{updatedDetails}");

            Assert.True(trimmedProcesses >= 0);
            Assert.True(freedBytes >= 0);
            Assert.False(string.IsNullOrWhiteSpace(updatedDetails));
            Assert.Contains("Cached (Standby):", updatedDetails);
            Assert.Contains("Free Memory:", updatedDetails);
        }

        [Fact]
        public void GetOsDescription_ReturnsAccurateOsName()
        {
            string os = HardwareDetailService.GetOsDescription();
            _output.WriteLine($"OS Description: {os}");

            Assert.False(string.IsNullOrWhiteSpace(os));
            if (Environment.OSVersion.Version.Build >= 22000)
            {
                Assert.Contains("Windows 11", os);
                Assert.DoesNotContain("Windows 10", os);
            }
        }
    }
}
